chore: 경로 소문자로 변경

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -32,12 +32,14 @@ jobs:
       - name: List files in src/statics
         run: find ./src/statics
       - name: Check Development/_data file
-        run: ls -l ./src/statics/Development/_data.ts || echo "File not found!"
+        run: ls -l ./src/statics/development/_data.ts || echo "File not found!"
 
       - name: Clear Cache
         run: rm -rf .next/cache
+
       - name: Build with Next.js
         run: NODE_ENV=production npm run build
+
       - name: Add .nojekyll file
         run: echo > ./out/.nojekyll
       - name: Upload artifact
